name: Deploy locally

on:
  push:
    branches:
      - main  # 每次推送到 main 分支時觸發
      - 'feature/*'
      - 'bugfix/*'

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # 同步最新CODE到指定路徑
    - name: Sync Latest Code to Remote Directory
      run: |
        mkdir -p ~/luboil_six
        rsync -av --delete --exclude '*.csv' --exclude '*.sh' --exclude '*.txt' --exclude 'querySql.py' --exclude '*.log' --exclude '.env' --exclude '*.json' --exclude '*.pkl' "$GITHUB_WORKSPACE"/ ~/luboil_six/
    
    - name: Build and Start Docker Containers
      run: |
        cd ~/luboil_six &&
        docker-compose down &&
        docker-compose up -d --build
